[package]
name = "pe"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
memory = { workspace = true }

anyhow = "1.0"
bitflags = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
