[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
serde_json = "1.0"
js-sys = "0.3.60"
log = "0.4.17"
console_log = "0.2.0"

[dependencies.win32]
path = "../win32"
version = "0.1.0"
