[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3.2"
log = "0.4.17"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
tsify = "0.4.1"
wasm-bindgen = "0.2.83"

[dependencies.x86]
path = "../x86"
version = "0.1.0"

[dependencies.win32-derive]
path = "derive"
version = "0.1.0"
