[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
memory = { workspace = true }
win32-derive = { path = "derive" }
x86 = { workspace = true, optional = true }

anyhow = "1.0"
bincode = "1.3.3"
bitflags = "1.3.2"
chrono = "0.4.38"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { version = "0.11.7", optional = true }

tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dependencies.unicorn-engine]
version = "2.0.0"
optional = true

[features]
wasm = ["dep:tsify", "dep:wasm-bindgen"]
x86-emu = ["dep:x86", "dep:serde_bytes"]
x86-64 = []
x86-unicorn = ["dep:unicorn-engine"]
