[package]
name = "win32"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3.2"
iced-x86 = "1.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.7"
wasm-bindgen = "0.2.83"
tsify = "0.4.1"
log = "0.4.17"
