[package]
name = "x86"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
memory = { workspace = true }

bitflags = "1.3.2"
iced-x86 = "1.17.0"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
tsify = "0.4.1"
wasm-bindgen = "0.2.83"
