[package]
name = "x86"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
memory = { workspace = true }

bitflags = "1.3.2"
futures = "0.3.30"
iced-x86 = "1.17.0"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }

tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[features]
wasm = ["dep:tsify", "dep:wasm-bindgen"]
